dist: xenial
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

sudo: true

before_install:
  - python --version
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt-get update
  - sudo apt-get install build-essential
  - pip -V
  - pip install --upgrade pip
  - pip install setuptools
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov

install:
  - python setup.py develop

script:
  - pytest --cov=./styled tests/test_styled.py

after_success:
  - coveralls