# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  #  branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  test:
    #TODO uncomment when done to ensure only run on
    #     base and not any fork/head repo
    if: github.repository_owner == 'emdb-empiar'

    name: ${{ matrix.os}} ${{ matrix.architecture }}, Python ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 2.7, 3.6, 3.7, 3.8 ] #, 3.9]
        architecture: [ x64 ]
        exclude:
          - os: windows-latest
            python-version: 2.7
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.architecture }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Setup and update Python and Pip environment
        run: |
          python -m pip install --upgrade pip setuptools wheel virtualenv
          python -m pip install --upgrade coveralls
      - name: Check for additional requirements
        id: check_requirements
        uses: andstor/file-existence-action@v1
        with:
          files: "requirements.txt"
      - name: Install addtional requirements
        if: steps.check_requirements.outputs.files_exists == 'true'
        run: |
          pip install -r requirements.txt
      - name: Install dependencies
        run: |
          pip install tox tox-gh-actions
          python -m pip install -e .
      - name: Test with pytest
        run: |
          tox
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Coveralls python 2.7 preconditions
        if : ${{ matrix.python-version == '2.7' }} 
        # tell coveralls that coverage used .coveragerc_27 configfile
        # coveralls for python2.7 is not yet aware of github actions.
        # luckily on python3 coveralls automatically uses secrets.github_token
        # as value for COVERALLS_REPO_TOKEN. For Python 2.7
        # COVERALLS_REPO_TOKEN enviroment varaiable is explicitly set to
        # secrets.github_token
        run: |
          echo "COVERAGE_RCFILE=.coveragerc_27" >> $GITHUB_ENV
          echo "COVERALLS_REPO_TOKEN=${{secrets.github_token}}" >> $GITHUB_ENV
      - name: Coveralls recent python preconditions
        if : ${{ matrix.python-version != '2.7' }}
        run: echo "COVERAGE_RCFILE=.coveragerc" >> $GITHUB_ENV
      - name: Compile coverage reports
        #if: ${{ success() && github.repository_owner == 'emdb-empiar' }}
        #uses: AndreMiras/coveralls-python-action@develop
        #uses: coverallsapp/github-action@master
        run: |
            coveralls --service=github --rcfile=${{ env.COVERAGE_RCFILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          COVERALLS_FLAG_NAME: run-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.architecture }}
          COVERALLS_PARALLEL: true

  coveralls:
    if: github.repository_owner == 'emdb-empiar'
    name: Indicate completion to coveralls.io
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Coveralls Finished
        #uses: AndreMiras/coveralls-python-action@develop
        #uses: coverallsapp/github-action@master
        run: |
            python -m pip install --upgrade pip setuptools wheel virtualenv
            python -m pip install --upgrade coveralls
            coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

